#services:
#  mongo:
#    image: mongo
#    container_name: mongodb
#    ports:
#      - 27017:27017
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=adminUser
#      - MONGO_INITDB_ROOT_PASSWORD=adminPassword
