name: backend

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      hostName: 127.0.0.1
      mongoUsername: adminUser
      mongoPassword: adminPassword
      portNumber: 27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install -B

      - name: Run tests
        run: mvn test
